In [1]:
import numpy as np

In [2]:
import pickle

In [3]:
import os
os.getcwd()

'c:\\Users\\ritux\\OneDrive - Danmarks Tekniske Universitet\\Dokumenter\\Esbjerg\\4 - Models\\07_27'

!pip install "pandas==2.2.3" "numpy>=1.26,<2.0" --force-reinstall

In [4]:
import numpy as np
import pandas as pd
print(np.__version__)   # should be 1.26.4
print(pd.__version__)   # should be 2.2.3

1.26.4
2.2.3

In [5]:
import sys
import numpy.core.numeric as _numeric
sys.modules['numpy._core.numeric'] = _numeric
# You may need to alias the parent too:
import numpy.core
sys.modules['numpy._core'] = numpy.core

In [31]:
PATH_TO_FILE = "results/tables/run_history.pkl"
with open(PATH_TO_FILE, 'rb') as file:
    data = pickle.load(file)

In [7]:
data.keys()

Index(['Job Id', 'Dataset', 'Mode', 'Model', 'Parameters', 'Objective',
       'Component', 'Validation', 'Test', 'Training Time (s)'],
      dtype='object')

In [32]:
data

,Job Id,Dataset,Mode,Model,Parameters,Objective,Component,Validation,Test,Training Time (s)
0,61618440,econ_rcp_26,single,MLP,{'Profile': 'simple_mlp'},Econ,delay,"{'MSE': 2607590229232.9395, 'RMSE': 1614803.46...","{'MSE': 3013193662013.144, 'RMSE': 1735855.311...",14000.015306
1,61618441,econ_rcp_26,single,MLP,{'Profile': 'simple_mlp'},Econ,infra,"{'MSE': 8591278134.768112, 'RMSE': 92689.14788...","{'MSE': 9273906986.729113, 'RMSE': 96301.12661...",24830.758373
2,61618442,econ_rcp_26,single,Auto,{'Profile': 'small_bottleneck'},Econ,delay,"{'MSE': 2547733650949.395, 'RMSE': 1596162.163...","{'MSE': 2940181993176.5547, 'RMSE': 1714695.88...",7031.262371
3,61618443,econ_rcp_26,single,Auto,{'Profile': 'small_bottleneck'},Econ,infra,"{'MSE': 9113504883.436129, 'RMSE': 95464.67872...","{'MSE': 10129473072.933765, 'RMSE': 100645.283...",22790.829729
4,61618444,econ_rcp_26,single,VAE,{'Profile': 'small_vae'},Econ,delay,"{'MSE': 2551348794661.5386, 'RMSE': 1597294.21...","{'MSE': 2954324729124.901, 'RMSE': 1718814.919...",9793.878542
...,...,...,...,...,...,...,...,...,...,...
142,61661639,econ_combined,single,VAE,{'Profile': 'medium_vae'},Econ,cancel,"{'MSE': 25493159108782.684, 'RMSE': 5049075.07...","{'MSE': 26318006416525.914, 'RMSE': 5130107.83...",2996.139768
143,61661640,econ_combined,single,VAE,{'Profile': 'medium_vae'},Econ,infra,"{'MSE': 10604757973.262175, 'RMSE': 102979.405...","{'MSE': 10797729072.185993, 'RMSE': 103912.121...",20369.157297
144,61661641,econ_combined,single,GP,{'Profile': 'tiny_gp'},Econ,delay,"{'MSE': 6139882285755.099, 'RMSE': 2477878.585...","{'MSE': 6054485765666.808, 'RMSE': 2460586.467...",20869.518561
145,61661642,econ_combined,single,GP,{'Profile': 'tiny_gp'},Econ,cancel,"{'MSE': 20806016706302.59, 'RMSE': 4561361.277...","{'MSE': 20857381985021.246, 'RMSE': 4566988.28...",23891.641151
146,61665443,qol_combined,single,MLP,{'Profile': 'simple_mlp'},QoL,qol,"{'MSE': 1.075587904540091e-06, 'RMSE': 0.00103...","{'MSE': 1.0483600051391337e-06, 'RMSE': 0.0010...",1020.282836

In [35]:
data_multi = data[data["Mode"] == "multi"]
data_multi = data_multi[data_multi["Dataset"].isin(["econ_combined", "qol_combined"])]
data_multi


for component in ALL_COMPONENTS:
    print("\n")
    component_data = data_multi[data_multi["Component"] == component]
    print(f"Component: {component}")

    for model_family in profiles.keys():
        data_family = component_data[component_data["Model"] == model_family]
        # Get unique parameters for the model family present in data_family
        present_profiles = data_family["Parameters"].apply(lambda p: p["Profile"]).unique()
        print(f"  Model Family: {model_family}")
        # Get the best R2 score for each profile in the model family
        for profile in present_profiles:
            profile_data = data_family[data_family["Parameters"].apply(lambda p: p["Profile"] == profile)]
            if not profile_data.empty:
                best_r2_row = profile_data.loc[
                    profile_data.apply(
                        lambda r: r["Test"].get("R2", float("nan")), axis=1
                    ).idxmax() ]
                
                
                best_test = best_r2_row["Test"]
                print(
                    f"    Profile: {profile}, Best Test R2: {round(best_test.get('R2'), 4)},, Job Id: {best_r2_row['Job Id']}, "
                    f"Policy Kendall Tau: {round(best_test.get('Policy Kendall Tau'), 4)}, RMSE: {round(best_test.get('RMSE'), 4)}"
                    
                )
                if str(best_r2_row['Job Id']) in best_R2_row['Job Id'].values:
                    print("    This is best!")

Component: delay
  Model Family: MLP
  Model Family: Auto
  Model Family: VAE
  Model Family: GP
  Model Family: XGB
  Model Family: GNN


Component: cancel
  Model Family: MLP
  Model Family: Auto
  Model Family: VAE
  Model Family: GP
  Model Family: XGB
  Model Family: GNN


Component: infra
  Model Family: MLP
  Model Family: Auto
  Model Family: VAE
  Model Family: GP
  Model Family: XGB
  Model Family: GNN


Component: qol
  Model Family: MLP
    Profile: simple_mlp, Best Test R2: 0.9999,, Job Id: 61661619, Policy Kendall Tau: 0.4365, RMSE: 0.0016
  Model Family: Auto
    Profile: small_bottleneck, Best Test R2: 0.9999,, Job Id: 61661620, Policy Kendall Tau: 0.4365, RMSE: 0.0014
    Profile: medium_bottleneck, Best Test R2: 0.9999,, Job Id: 61661621, Policy Kendall Tau: 0.4365, RMSE: 0.0014
  Model Family: VAE
    Profile: small_vae, Best Test R2: 0.9999,, Job Id: 61661622, Policy Kendall Tau: 0.4365, RMSE: 0.0015
    Profile: medium_vae, Best Test R2: 0.9999,, Job Id: 61661623, Policy Kendall Tau: 0.4365, RMSE: 0.0014
  Model Family: GP
    Profile: tiny_gp, Best Test R2: 0.9987,, Job Id: 61661624, Policy Kendall Tau: 0.4535, RMSE: 0.0061
  Model Family: XGB
  Model Family: GNN
    Profile: small_gnn, Best Test R2: 0.9998,, Job Id: 61618580, Policy Kendall Tau: 0.4362, RMSE: 0.0027


Component: action
  Model Family: MLP
    Profile: simple_mlp, Best Test R2: 0.8571,, Job Id: 61661619, Policy Kendall Tau: 0.5074, RMSE: 26951023.13
  Model Family: Auto
    Profile: small_bottleneck, Best Test R2: 0.4184,, Job Id: 61661620, Policy Kendall Tau: 0.393, RMSE: 54374943.1128
    Profile: medium_bottleneck, Best Test R2: 0.4528,, Job Id: 61661621, Policy Kendall Tau: 0.3983, RMSE: 52744747.833
  Model Family: VAE
    Profile: small_vae, Best Test R2: 0.3198,, Job Id: 61661622, Policy Kendall Tau: 0.3529, RMSE: 58806414.6374
    Profile: medium_vae, Best Test R2: 0.2513,, Job Id: 61661623, Policy Kendall Tau: 0.3332, RMSE: 61694923.8884
  Model Family: GP
    Profile: tiny_gp, Best Test R2: 0.0328,, Job Id: 61661624, Policy Kendall Tau: 0.0243, RMSE: 70122644.9704
  Model Family: XGB
  Model Family: GNN
    Profile: small_gnn, Best Test R2: 0.9818,, Job Id: 61618580, Policy Kendall Tau: 0.6111, RMSE: 9624220.7209


Component: maintenance
  Model Family: MLP
    Profile: simple_mlp, Best Test R2: 0.9116,, Job Id: 61661619, Policy Kendall Tau: 0.8405, RMSE: 278898.0761
  Model Family: Auto
    Profile: small_bottleneck, Best Test R2: 0.9106,, Job Id: 61661620, Policy Kendall Tau: 0.8403, RMSE: 280521.2031
    Profile: medium_bottleneck, Best Test R2: 0.9107,, Job Id: 61661621, Policy Kendall Tau: 0.84, RMSE: 280447.832
  Model Family: VAE
    Profile: small_vae, Best Test R2: 0.9102,, Job Id: 61661622, Policy Kendall Tau: 0.8405, RMSE: 281149.3656
    Profile: medium_vae, Best Test R2: 0.9105,, Job Id: 61661623, Policy Kendall Tau: 0.8405, RMSE: 280735.2769
  Model Family: GP
    Profile: tiny_gp, Best Test R2: 0.7438,, Job Id: 61661624, Policy Kendall Tau: 0.7687, RMSE: 474918.6649
  Model Family: XGB
  Model Family: GNN
    Profile: small_gnn, Best Test R2: 0.9782,, Job Id: 61618580, Policy Kendall Tau: 0.9267, RMSE: 138426.9932

In [9]:
data_copy = data.copy()
data_copy["Parameters"] = data_copy["Parameters"].apply(lambda x: x['Profile'])
data_copy["Job Id"] = data_copy["Job Id"].apply(lambda x: int(x) if x.isdigit() else int(x[:-3]+x[-2]))

# data_copy["Test"] = data_copy["Test"].apply(lambda x: x[''])
data_copy

,Job Id,Dataset,Mode,Model,Parameters,Objective,Component,Validation,Test,Training Time (s)
0,61618440,econ_rcp_26,single,MLP,simple_mlp,Econ,delay,"{'MSE': 2607590229232.9395, 'RMSE': 1614803.46...","{'MSE': 3013193662013.144, 'RMSE': 1735855.311...",14000.015306
1,61618441,econ_rcp_26,single,MLP,simple_mlp,Econ,infra,"{'MSE': 8591278134.768112, 'RMSE': 92689.14788...","{'MSE': 9273906986.729113, 'RMSE': 96301.12661...",24830.758373
2,61618442,econ_rcp_26,single,Auto,small_bottleneck,Econ,delay,"{'MSE': 2547733650949.395, 'RMSE': 1596162.163...","{'MSE': 2940181993176.5547, 'RMSE': 1714695.88...",7031.262371
3,61618443,econ_rcp_26,single,Auto,small_bottleneck,Econ,infra,"{'MSE': 9113504883.436129, 'RMSE': 95464.67872...","{'MSE': 10129473072.933765, 'RMSE': 100645.283...",22790.829729
4,61618444,econ_rcp_26,single,VAE,small_vae,Econ,delay,"{'MSE': 2551348794661.5386, 'RMSE': 1597294.21...","{'MSE': 2954324729124.901, 'RMSE': 1718814.919...",9793.878542
...,...,...,...,...,...,...,...,...,...,...
89,616259060,qol_combined,single,GNN,small_gnn,QoL,maintenance,"{'MSE': 19527342728.750782, 'RMSE': 139740.268...","{'MSE': 19405303911.402206, 'RMSE': 139302.921...",8633.322829
90,616259061,qol_combined,single,GNN,small_gnn,QoL,maintenance,"{'MSE': 18245444210.79755, 'RMSE': 135075.6980...","{'MSE': 18147655692.179043, 'RMSE': 134713.235...",16724.917592
91,616259062,qol_combined,single,GNN,small_gnn,QoL,maintenance,"{'MSE': 17844074371.63439, 'RMSE': 133581.7142...","{'MSE': 17756195282.03279, 'RMSE': 133252.3743...",23319.472095
92,616259063,qol_combined,single,GNN,small_gnn,QoL,maintenance,"{'MSE': 17550124102.137264, 'RMSE': 132476.881...","{'MSE': 17473311307.59528, 'RMSE': 132186.6532...",31165.857554
93,616259064,qol_combined,single,GNN,small_gnn,QoL,maintenance,"{'MSE': 17266552167.555336, 'RMSE': 131402.253...","{'MSE': 17197716274.031937, 'RMSE': 131140.063...",44662.673443

In [ ]:
data_copy["Test"] = data_copy["Test"].apply(lambda x: x['Test'].items())

0     {'MSE': 3013193662013.144, 'RMSE': 1735855.311...
1     {'MSE': 9273906986.729113, 'RMSE': 96301.12661...
2     {'MSE': 2940181993176.5547, 'RMSE': 1714695.88...
3     {'MSE': 10129473072.933765, 'RMSE': 100645.283...
4     {'MSE': 2954324729124.901, 'RMSE': 1718814.919...
5     {'MSE': 10942636402.586575, 'RMSE': 104607.057...
6     {'MSE': 1.9869751588525053e-06, 'RMSE': 0.0014...
7     {'MSE': 2.046416447287299e-06, 'RMSE': 0.00143...
8     {'MSE': 2.6615631495333234e-06, 'RMSE': 0.0016...
9     {'MSE': 6.639209775708755e-06, 'RMSE': 0.00257...
10    {'MSE': 4.984572956282778e-07, 'RMSE': 0.00070...
11    {'MSE': 1.3684839137396708e-05, 'RMSE': 0.0036...
12    {'MSE': 16215742128970.56, 'RMSE': 4026877.466...
13    {'MSE': 5.03250957991377e-06, 'RMSE': 0.002243...
14    {'MSE': 61305545967178.1, 'RMSE': 7829785.8187...
15    {'MSE': 17197716274.031937, 'RMSE': 131140.063...
16    {'MSE': 7.050234671062896e-06, 'RMSE': 0.00265...
17    {'MSE': 92625624484110.66, 'RMSE': 9624220.720...
18    {'MSE': 19162032434.421677, 'RMSE': 138426.993...
19    {'MSE': 1.9869751588525053e-06, 'RMSE': 0.0014...
20    {'MSE': 1.9869751588525053e-06, 'RMSE': 0.0014...
21    {'MSE': 1.9869751588525053e-06, 'RMSE': 0.0014...
22    {'MSE': 1.9869751588525053e-06, 'RMSE': 0.0014...
23    {'MSE': 1.9869751588525053e-06, 'RMSE': 0.0014...
Name: Test, dtype: object

In [48]:
row['Job Id'][:-3]+row['Job Id'][-2]

'616185874'

In [52]:
# Get row with Job Id = 61582379
row = data.iloc[-1]
for column in row.keys():
    print(f" {row[column]}")
print("#####")
print(type(row['Validation']))
for key, val in row['Test'].items():
    print(f"{key}: {val}")

 61618587[4]
 qol_rcp_45
 single
 MLP
 {'Profile': 'simple_mlp'}
 QoL
 qol
 {'MSE': 1.965010450928016e-06, 'RMSE': 0.0014017883046052338, 'MAE': 0.00021047280479188077, 'R2': 0.9999307185072994, 'Max Absolute Error': 0.10841284692287445, 'Values': 1605450, 'Policy Kendall Tau': 0.4373672639058976, 'Policy Spearman': 0.5225772712710064, 'Policy Metrics Note': 'ok', 'Policy Aggregate Kendall Tau': 0.9356218100326962, 'Policy Aggregate Spearman': 0.9932378602302534, 'Policy Aggregate Metrics Note': 'ok'}
 {'MSE': 1.9869751588525053e-06, 'RMSE': 0.0014096010637242387, 'MAE': 0.0002119762391309558, 'R2': 0.9999299421167691, 'Max Absolute Error': 0.10885600745677948, 'Values': 3210900, 'Policy Kendall Tau': 0.43687076066838154, 'Policy Spearman': 0.5220152364575653, 'Policy Metrics Note': 'ok', 'Policy Aggregate Kendall Tau': 0.9321712624739052, 'Policy Aggregate Spearman': 0.9926911508156059, 'Policy Aggregate Metrics Note': 'ok'}
 168.3244416359812
#####
<class 'dict'>
MSE: 1.9869751588525053e-06
RMSE: 0.0014096010637242387
MAE: 0.0002119762391309558
R2: 0.9999299421167691
Max Absolute Error: 0.10885600745677948
Values: 3210900
Policy Kendall Tau: 0.43687076066838154
Policy Spearman: 0.5220152364575653
Policy Metrics Note: ok
Policy Aggregate Kendall Tau: 0.9321712624739052
Policy Aggregate Spearman: 0.9926911508156059
Policy Aggregate Metrics Note: ok

In [26]:
# Best Test R2 result for each Component
best_r2_results = data.groupby("Component").apply(
    lambda g: max(
        row.get("R2", float("nan")) for _, row in g.iterrows()
    )
)
best_r2_results

Component
action        NaN
cancel        NaN
delay         NaN
infra         NaN
maintenance   NaN
qol           NaN
dtype: float64

In [9]:
data_cancel = data[data["Component"] == "cancel"]
for row in data_cancel.itertuples():
    print(f"    Job ID: {row._1}, Model: {row.Model}, Parameters: {row.Parameters['Profile']}")
    print(f"    Data: {row.Dataset}, Mode: {row.Mode}")
    print(f"    Best Test R2: {row.Test['R2']}")
    print(f"    MSE: {row.Test['MSE']}, MAE: {row.Test['MAE']}")
    print(f"    Policy: {row.Test['Policy Kendall Tau']}")
    print("\n")

    Job ID: 61618547, Model: GNN, Parameters: small_gnn
    Data: econ_combined, Mode: single
    Best Test R2: 0.24468869327297682
    MSE: 16215742128970.56, MAE: 1234159.8330439755
    Policy: 0.3241394019591284


    Job ID: 61625820, Model: MLP, Parameters: simple_mlp
    Data: econ_rcp_45, Mode: single
    Best Test R2: -0.33934535799691634
    MSE: 15244452881089.896, MAE: 1274232.0140857415
    Policy: 0.22075349555007212


    Job ID: 61625822, Model: MLP, Parameters: deep_mlp
    Data: econ_rcp_45, Mode: single
    Best Test R2: -0.4997218080524104
    MSE: 17069860511399.596, MAE: 1322850.0584844116
    Policy: 0.20429991365357264


    Job ID: 61625824, Model: MLP, Parameters: wide_mlp
    Data: econ_rcp_45, Mode: single
    Best Test R2: -0.4003419645684352
    MSE: 15938717350842.916, MAE: 1306590.6473130165
    Policy: 0.23132690300225314


    Job ID: 61625826, Model: Auto, Parameters: small_bottleneck
    Data: econ_rcp_45, Mode: single
    Best Test R2: -0.5184269563864208
    MSE: 17282762845147.242, MAE: 1281643.7379478477
    Policy: 0.2299140418205687


    Job ID: 61625828, Model: Auto, Parameters: deep_bottleneck
    Data: econ_rcp_45, Mode: single
    Best Test R2: -0.6136061542558815
    MSE: 18366094181995.96, MAE: 1300121.6665886862
    Policy: 0.2146304862924617


    Job ID: 61625830, Model: Auto, Parameters: medium_bottleneck
    Data: econ_rcp_45, Mode: single
    Best Test R2: -0.4991033513291958
    MSE: 17062821225886.158, MAE: 1272650.5670293123
    Policy: 0.23803900518232796


    Job ID: 61625832, Model: Auto, Parameters: wide_bottleneck
    Data: econ_rcp_45, Mode: single
    Best Test R2: -0.5696129011569806
    MSE: 17865362186362.61, MAE: 1302771.830290283
    Policy: 0.21725769538472336


    Job ID: 61625834, Model: VAE, Parameters: small_vae
    Data: econ_rcp_45, Mode: single
    Best Test R2: -0.6198666062381433
    MSE: 18437350758716.883, MAE: 1294218.13889076
    Policy: 0.19664610396827364


    Job ID: 61625836, Model: VAE, Parameters: medium_vae
    Data: econ_rcp_45, Mode: single
    Best Test R2: -0.6057567202166225
    MSE: 18276751783009.59, MAE: 1279169.419428637
    Policy: 0.17974578145429984


    Job ID: 61625838, Model: VAE, Parameters: wide_vae
    Data: econ_rcp_45, Mode: single
    Best Test R2: -0.5852099120794074
    MSE: 18042887644358.285, MAE: 1270124.7458016674
    Policy: 0.2013257987840524


    Job ID: 61625840, Model: VAE, Parameters: large_vae
    Data: econ_rcp_45, Mode: single
    Best Test R2: -0.5529040922631916
    MSE: 17675182223920.773, MAE: 1266644.8617304284
    Policy: 0.21532768234662528


    Job ID: 61625842, Model: GP, Parameters: small_gp
    Data: econ_rcp_45, Mode: single
    Best Test R2: -2.0676018192581878
    MSE: 34915496346581.746, MAE: 1402201.5291498604
    Policy: 0.2684070977341386


    Job ID: 61625852, Model: GNN, Parameters: small_gnn
    Data: econ_rcp_45, Mode: single
    Best Test R2: 0.04033412677570092
    MSE: 10922934177214.283, MAE: 1216783.1975357195
    Policy: 0.2889416564242627


    Job ID: 61625854, Model: GNN, Parameters: medium_gnn
    Data: econ_rcp_45, Mode: single
    Best Test R2: 0.03792502018070032
    MSE: 10950354671677.291, MAE: 1217365.5748671978
    Policy: 0.28966461374641506


    Job ID: 61625858, Model: MLP, Parameters: simple_mlp
    Data: econ_combined, Mode: single
    Best Test R2: 0.11257032647109877
    MSE: 19052184993626.74, MAE: 1328752.7772083057
    Policy: 0.259325439610184


    Job ID: 61625860, Model: MLP, Parameters: deep_mlp
    Data: econ_combined, Mode: single
    Best Test R2: 0.0026271450510172434
    MSE: 21412549869497.707, MAE: 1389713.1672652825
    Policy: 0.22717736142224979


    Job ID: 61625862, Model: MLP, Parameters: wide_mlp
    Data: econ_combined, Mode: single
    Best Test R2: 0.23060399029491885
    MSE: 16518125940017.99, MAE: 1234694.3730470953
    Policy: 0.31163522840706653


    Job ID: 61625864, Model: Auto, Parameters: small_bottleneck
    Data: econ_combined, Mode: single
    Best Test R2: 0.026282002854009834
    MSE: 20904704864644.066, MAE: 1350415.9749946774
    Policy: 0.2073186890942732


    Job ID: 61625866, Model: Auto, Parameters: deep_bottleneck
    Data: econ_combined, Mode: single
    Best Test R2: -0.10403905310604
    MSE: 23702561349251.227, MAE: 1447039.5771032223
    Policy: 0.17120378505144357


    Job ID: 61625868, Model: Auto, Parameters: medium_bottleneck
    Data: econ_combined, Mode: single
    Best Test R2: -0.12180808147110112
    MSE: 24084043764890.918, MAE: 1454654.729786155
    Policy: 0.16874673608081206


    Job ID: 61625870, Model: Auto, Parameters: wide_bottleneck
    Data: econ_combined, Mode: single
    Best Test R2: -0.17108927537529728
    MSE: 25142059347394.375, MAE: 1470365.7620024704
    Policy: 0.15663908803609006


    Job ID: 61625872, Model: VAE, Parameters: small_vae
    Data: econ_combined, Mode: single
    Best Test R2: -0.1174001587939364
    MSE: 23989410284866.53, MAE: 1396244.5143799654
    Policy: 0.18187089720984503


    Job ID: 61625874, Model: VAE, Parameters: medium_vae
    Data: econ_combined, Mode: single
    Best Test R2: -0.14523250034112034
    MSE: 24586941487371.992, MAE: 1391388.8379114848
    Policy: 0.1638214240634265


    Job ID: 61625876, Model: VAE, Parameters: wide_vae
    Data: econ_combined, Mode: single
    Best Test R2: -0.1272261155661505
    MSE: 24200363278379.996, MAE: 1371395.998848026
    Policy: 0.1790696189165578


    Job ID: 61625878, Model: VAE, Parameters: large_vae
    Data: econ_combined, Mode: single
    Best Test R2: -0.09808411800397954
    MSE: 23574715133856.67, MAE: 1403359.9581466827
    Policy: 0.19532889418322794


    Job ID: 61625890, Model: GNN, Parameters: small_gnn
    Data: econ_combined, Mode: single
    Best Test R2: 0.24468869327297682
    MSE: 16215742128970.56, MAE: 1234159.8330439755
    Policy: 0.3241394019591284


    Job ID: 61625904[0], Model: GNN, Parameters: small_gnn
    Data: econ_combined, Mode: single
    Best Test R2: 0.10874486192839938
    MSE: 19134313707966.707, MAE: 1235090.736266382
    Policy: 0.27231423358798434


    Job ID: 61625904[1], Model: GNN, Parameters: small_gnn
    Data: econ_combined, Mode: single
    Best Test R2: 0.2168547441805302
    MSE: 16813307843787.973, MAE: 1206022.5988530605
    Policy: 0.30304694243505675


    Job ID: 61625904[2], Model: GNN, Parameters: small_gnn
    Data: econ_combined, Mode: single
    Best Test R2: 0.24632358914656638
    MSE: 16180642628065.793, MAE: 1206472.356546773
    Policy: 0.3167231275269446


    Job ID: 61625904[3], Model: GNN, Parameters: small_gnn
    Data: econ_combined, Mode: single
    Best Test R2: 0.24543073897533008
    MSE: 16199811185464.082, MAE: 1195638.5781793168
    Policy: 0.3242163358911979


    Job ID: 61625904[4], Model: GNN, Parameters: small_gnn
    Data: econ_combined, Mode: single
    Best Test R2: 0.24468869327297682
    MSE: 16215742128970.56, MAE: 1234159.8330439755
    Policy: 0.3241394019591284


    Job ID: 61641456, Model: GNN, Parameters: small_gnn
    Data: econ_combined, Mode: single
    Best Test R2: 0.24468869327297682
    MSE: 16215742128970.56, MAE: 1234159.8330439755
    Policy: 0.3241394019591284


    Job ID: 61661556, Model: GP, Parameters: tiny_gp
    Data: econ_combined, Mode: single
    Best Test R2: 0.02848616921801228
    MSE: 20857381985021.246, MAE: 1285150.0483886814
    Policy: 0.24450290714615555


    Job ID: 61661598, Model: GP, Parameters: tiny_gp
    Data: econ_combined, Mode: single
    Best Test R2: -0.01191488970386212
    MSE: 21724750304270.61, MAE: 1362561.6267390628
    Policy: 0.17722210755358492


    Job ID: 61661604, Model: GNN, Parameters: small_gnn
    Data: econ_combined, Mode: single
    Best Test R2: 0.24468869327297682
    MSE: 16215742128970.56, MAE: 1234159.8330439755
    Policy: 0.3241394019591284


    Job ID: 61661627, Model: MLP, Parameters: simple_mlp
    Data: econ_combined, Mode: single
    Best Test R2: -0.13449442155454583
    MSE: 24356406190186.78, MAE: 1374142.48769838
    Policy: 0.19463487937290616


    Job ID: 61661630, Model: Auto, Parameters: small_bottleneck
    Data: econ_combined, Mode: single
    Best Test R2: -0.22622677118235401
    MSE: 26325803593881.027, MAE: 1355416.614828632
    Policy: 0.17935805418112133


    Job ID: 61661633, Model: Auto, Parameters: medium_bottleneck
    Data: econ_combined, Mode: single
    Best Test R2: -0.20819875931906906
    MSE: 25938761073969.82, MAE: 1357561.0267758898
    Policy: 0.1785844151324978


    Job ID: 61661636, Model: VAE, Parameters: small_vae
    Data: econ_combined, Mode: single
    Best Test R2: -0.24025894682358762
    MSE: 26627059698059.67, MAE: 1347316.0043361979
    Policy: 0.16013651599340017


    Job ID: 61661639, Model: VAE, Parameters: medium_vae
    Data: econ_combined, Mode: single
    Best Test R2: -0.22586358729782807
    MSE: 26318006416525.914, MAE: 1336610.2944232915
    Policy: 0.16928962954394236


    Job ID: 61661642, Model: GP, Parameters: tiny_gp
    Data: econ_combined, Mode: single
    Best Test R2: 0.02848616921801228
    MSE: 20857381985021.246, MAE: 1285150.0483886814
    Policy: 0.24450290714615555

In [10]:
data_cancel = data[data["Component"] == "delay"]
for row in data_cancel.itertuples():
    print(f"    Job ID: {row._1}, Model: {row.Model}, Parameters: {row.Parameters['Profile']}")
    print(f"    Best Test R2: {row.Test['R2']}")
    print(f"    MSE: {row.Test['MSE']}, MAE: {row.Test['MAE']}")
    print(f"    Policy: {row.Test['Policy Kendall Tau']}")
    print("\n")

    Job ID: 61618440, Model: MLP, Parameters: simple_mlp
    Best Test R2: 0.6859772299530684
    MSE: 3013193662013.144, MAE: 562099.0012105874
    Policy: 0.6980684248553299


    Job ID: 61618442, Model: Auto, Parameters: small_bottleneck
    Best Test R2: 0.6935862086864489
    MSE: 2940181993176.5547, MAE: 550618.6534386275
    Policy: 0.6962081422232176


    Job ID: 61618444, Model: VAE, Parameters: small_vae
    Best Test R2: 0.6921123103524218
    MSE: 2954324729124.901, MAE: 550764.9400230942
    Policy: 0.7008214818627985


    Job ID: 61625819, Model: MLP, Parameters: simple_mlp
    Best Test R2: 0.6466999205756965
    MSE: 3556520942517.04, MAE: 588387.5186270796
    Policy: 0.698634044561509


    Job ID: 61625821, Model: MLP, Parameters: deep_mlp
    Best Test R2: 0.6474253516340436
    MSE: 3549218338012.767, MAE: 583709.6774538086
    Policy: 0.702004471579124


    Job ID: 61625825, Model: Auto, Parameters: small_bottleneck
    Best Test R2: 0.6445480458557491
    MSE: 3578182945875.875, MAE: 583321.2171428668
    Policy: 0.7018637468325295


    Job ID: 61625827, Model: Auto, Parameters: deep_bottleneck
    Best Test R2: 0.6475466595717485
    MSE: 3547997182835.9995, MAE: 583219.7925737936
    Policy: 0.7019128186066439


    Job ID: 61625829, Model: Auto, Parameters: medium_bottleneck
    Best Test R2: 0.6459498106120563
    MSE: 3564071979016.1655, MAE: 583950.5040838366
    Policy: 0.6988864286435944


    Job ID: 61625831, Model: Auto, Parameters: wide_bottleneck
    Best Test R2: 0.6465571214020995
    MSE: 3557958440782.817, MAE: 583276.5523520779
    Policy: 0.6985113992185488


    Job ID: 61625833, Model: VAE, Parameters: small_vae
    Best Test R2: 0.6482943345294653
    MSE: 3540470658501.0825, MAE: 581547.6154349248
    Policy: 0.702027127983261


    Job ID: 61625835, Model: VAE, Parameters: medium_vae
    Best Test R2: 0.6334318077918026
    MSE: 3690085364751.2188, MAE: 616789.3817884382
    Policy: 0.6869219301300051


    Job ID: 61625837, Model: VAE, Parameters: wide_vae
    Best Test R2: 0.3854927215320014
    MSE: 6185982207425.018, MAE: 717615.355470622
    Policy: 0.6609661929864576


    Job ID: 61625839, Model: VAE, Parameters: large_vae
    Best Test R2: 0.6433351867823822
    MSE: 3590392279940.5024, MAE: 592103.9691728345
    Policy: 0.6997071481580984


    Job ID: 61625857, Model: MLP, Parameters: simple_mlp
    Best Test R2: 0.6260234737309899
    MSE: 3251530024073.487, MAE: 565159.4441908766
    Policy: 0.6965378364313479


    Job ID: 61625859, Model: MLP, Parameters: deep_mlp
    Best Test R2: 0.6310934110976684
    MSE: 3207449574072.01, MAE: 558854.737454829
    Policy: 0.6983448511140001


    Job ID: 61625863, Model: Auto, Parameters: small_bottleneck
    Best Test R2: 0.6269197179212498
    MSE: 3243737650250.978, MAE: 559522.0706702073
    Policy: 0.6996194442540002


    Job ID: 61625865, Model: Auto, Parameters: deep_bottleneck
    Best Test R2: 0.6258886830636992
    MSE: 3252701958328.381, MAE: 559300.1351489252
    Policy: 0.6989969822531525


    Job ID: 61625867, Model: Auto, Parameters: medium_bottleneck
    Best Test R2: 0.6261733831899028
    MSE: 3250226639843.972, MAE: 559873.2791430563
    Policy: 0.6997032642511657


    Job ID: 61625869, Model: Auto, Parameters: wide_bottleneck
    Best Test R2: 0.6327275825834409
    MSE: 3193241308907.6562, MAE: 550736.1724276368
    Policy: 0.6976359278106083


    Job ID: 61625871, Model: VAE, Parameters: small_vae
    Best Test R2: 0.6242687751632279
    MSE: 3266786209089.1553, MAE: 561749.3994788026
    Policy: 0.6986566852842984


    Job ID: 61625873, Model: VAE, Parameters: medium_vae
    Best Test R2: 0.5807449025946616
    MSE: 3645203485254.889, MAE: 610938.7702784465
    Policy: 0.6784685498703286


    Job ID: 61625875, Model: VAE, Parameters: wide_vae
    Best Test R2: 0.39496045934146007
    MSE: 5260501913929.607, MAE: 711401.7533147122
    Policy: 0.6263247068373432


    Job ID: 61625877, Model: VAE, Parameters: large_vae
    Best Test R2: 0.08558960141221628
    MSE: 7950319489289.193, MAE: 735616.4552567522
    Policy: 0.6401598185722126


    Job ID: 61625901[0], Model: Auto, Parameters: small_bottleneck
    Best Test R2: 0.37859834443519
    MSE: 5402761933310.631, MAE: 710789.6443553483
    Policy: 0.6226349426993821


    Job ID: 61625901[1], Model: Auto, Parameters: small_bottleneck
    Best Test R2: 0.40268413237844103
    MSE: 5193348622180.474, MAE: 663434.1486610053
    Policy: 0.629836670383319


    Job ID: 61625901[2], Model: Auto, Parameters: small_bottleneck
    Best Test R2: 0.3999881503542111
    MSE: 5216788773848.818, MAE: 692427.0852252963
    Policy: 0.6305590320433032


    Job ID: 61625901[3], Model: Auto, Parameters: small_bottleneck
    Best Test R2: 0.6286429138007592
    MSE: 3228755364609.995, MAE: 556771.5773639039
    Policy: 0.7002338601969201


    Job ID: 61625901[4], Model: Auto, Parameters: small_bottleneck
    Best Test R2: 0.6269197179212498
    MSE: 3243737650250.978, MAE: 559522.0706702073
    Policy: 0.6996194442540002


    Job ID: 61661495, Model: MLP, Parameters: simple_mlp
    Best Test R2: 0.4518330811103991
    MSE: 4766024254932.205, MAE: 678724.754940534
    Policy: 0.63224014344021


    Job ID: 61661626, Model: MLP, Parameters: simple_mlp
    Best Test R2: 0.4518330811103991
    MSE: 4766024254932.205, MAE: 678724.754940534
    Policy: 0.63224014344021


    Job ID: 61661629, Model: Auto, Parameters: small_bottleneck
    Best Test R2: 0.40268413237844103
    MSE: 5193348622180.474, MAE: 663434.1486610053
    Policy: 0.629836670383319


    Job ID: 61661632, Model: Auto, Parameters: medium_bottleneck
    Best Test R2: 0.39328483373255274
    MSE: 5275070600982.841, MAE: 669322.2178502129
    Policy: 0.6251957101844806


    Job ID: 61661635, Model: VAE, Parameters: small_vae
    Best Test R2: 0.3777940636149614
    MSE: 5409754733796.935, MAE: 668496.9453970169
    Policy: 0.62589324203738


    Job ID: 61661638, Model: VAE, Parameters: medium_vae
    Best Test R2: 0.36016985799030465
    MSE: 5562987970948.816, MAE: 675743.3954782678
    Policy: 0.6245836670117181


    Job ID: 61661641, Model: GP, Parameters: tiny_gp
    Best Test R2: 0.30364001238924554
    MSE: 6054485765666.808, MAE: 790388.9507187346
    Policy: 0.6135117247893367

In [22]:
# Get the row with the best Test R2 result for each Component
best_R2_row = data[data["Dataset"].isin(["econ_combined", "qol_combined"])].loc[
    data[data["Dataset"].isin(["econ_combined", "qol_combined"])].apply(lambda r: r["Test"].get("R2", float("nan")), axis=1)
    .groupby(data[data["Dataset"].isin(["econ_combined", "qol_combined"])]["Component"])
    .idxmax()
]

for component, row in best_R2_row.iterrows():
    print(f"Component: {row['Component']}")
    print(f"    Job ID: {row['Job Id']}, Model: {row['Model']}, Parameters: {row['Parameters']['Profile']}")
    print(f"    Best Test R2: {row['Test']['R2']}")
    print(f"    MSE: {row['Test']['MSE']}, MAE: {row['Test']['MAE']}")
    print(f"    Policy: {row['Test']['Policy Kendall Tau']}")

Component: action
    Job ID: 61618565, Model: GNN, Parameters: small_gnn
    Best Test R2: 0.9879413018451796
    MSE: 61305545967178.1, MAE: 2683222.236427711
    Policy: 0.613338608082169
Component: cancel
    Job ID: 61625904[2], Model: GNN, Parameters: small_gnn
    Best Test R2: 0.24632358914656638
    MSE: 16180642628065.793, MAE: 1206472.356546773
    Policy: 0.3167231275269446
Component: delay
    Job ID: 61625869, Model: Auto, Parameters: wide_bottleneck
    Best Test R2: 0.6327275825834409
    MSE: 3193241308907.6562, MAE: 550736.1724276368
    Policy: 0.6976359278106083
Component: infra
    Job ID: 61625902[1], Model: MLP, Parameters: simple_mlp
    Best Test R2: 0.9974443374384782
    MSE: 9506179062.011757, MAE: 15530.06607250644
    Policy: 0.9369005233794834
Component: maintenance
    Job ID: 61618566, Model: GNN, Parameters: small_gnn
    Best Test R2: 0.9804639205117373
    MSE: 17197716274.031937, MAE: 50911.8297350039
    Policy: 0.9358643626706269
Component: qol
    Job ID: 61625903[0], Model: XGB, Parameters: small_xgb
    Best Test R2: 0.99998604818605
    MSE: 3.967249370581927e-07, MAE: 9.80963646605116e-05
    Policy: 0.9996748418150013

In [33]:
# Get the row with the best Test MSE result for each Component
best_MSE_row = data.loc[
    data.apply(lambda r: r["Test"].get("MSE", float("inf")), axis=1)
    .groupby(data["Component"])
    .idxmin()
]

for component, row in best_MSE_row.iterrows():
    print(f"Component: {row['Component']}")
    print(f"    Job ID: {row['Job Id']}, Model: {row['Model']}, Parameters: {row['Parameters']['Profile']}")
    print(f"    Best Test MSE: {row['Test']['MSE']}")
    print(f"    R2: {row['Test']['R2']}, MAE: {row['Test']['MAE']}")

Component: action
    Job ID: 61618565, Model: GNN, Parameters: small_gnn
    Best Test MSE: 61305545967178.1
    R2: 0.9879413018451796, MAE: 2683222.236427711
Component: cancel
    Job ID: 61625904[2], Model: GNN, Parameters: small_gnn
    Best Test MSE: 16180642628065.793
    R2: 0.24632358914656638, MAE: 1206472.356546773
Component: delay
    Job ID: 61625869, Model: Auto, Parameters: wide_bottleneck
    Best Test MSE: 3193241308907.6562
    R2: 0.6327275825834409, MAE: 550736.1724276368
Component: infra
    Job ID: 61625902[1], Model: MLP, Parameters: simple_mlp
    Best Test MSE: 9506179062.011757
    R2: 0.9974443374384782, MAE: 15530.06607250644
Component: maintenance
    Job ID: 61618566, Model: GNN, Parameters: small_gnn
    Best Test MSE: 17197716274.031937
    R2: 0.9804639205117373, MAE: 50911.8297350039
Component: qol
    Job ID: 61625903[0], Model: XGB, Parameters: small_xgb
    Best Test MSE: 3.967249370581927e-07
    R2: 0.99998604818605, MAE: 9.80963646605116e-05

In [34]:
# Get the row with the best Test Policy Kendall Tau result for each Component
best_Kendall_Tau_row = data.loc[
    data.apply(
        lambda r: r["Test"].get("Policy Kendall Tau", float("inf")),
        axis=1,
    )
    .groupby(data["Component"])
    .idxmax()
]

for component, row in best_Kendall_Tau_row.iterrows():
    print(f"Component: {row['Component']}")
    print(f"    Job ID: {row['Job Id']}, Model: {row['Model']}, Parameters: {row['Parameters']['Profile']}")
    print(f"    Best Policy Kendall Tau: {row['Test'].get('Policy Kendall Tau')}")
    print(f"    Policy Spearman: {row['Test'].get('Policy Spearman')}")
    print(f"    Policy Aggregate Kendall Tau: {row['Test'].get('Policy Aggregate Kendall Tau')}")
    print(f"    R2: {row['Test'].get('R2')}")

Component: action
    Job ID: 61618565, Model: GNN, Parameters: small_gnn
    Best Policy Kendall Tau: 0.613338608082169
    Policy Spearman: 0.719005563527453
    Policy Aggregate Kendall Tau: 0.9665179015369668
    R2: 0.9879413018451796
Component: cancel
    Job ID: 61625904[3], Model: GNN, Parameters: small_gnn
    Best Policy Kendall Tau: 0.3242163358911979
    Policy Spearman: 0.40308802065340876
    Policy Aggregate Kendall Tau: 0.727496737952107
    R2: 0.24543073897533008
Component: delay
    Job ID: 61625901[3], Model: Auto, Parameters: small_bottleneck
    Best Policy Kendall Tau: 0.7002338601969201
    Policy Spearman: 0.8489202699198353
    Policy Aggregate Kendall Tau: 0.8705998820968903
    R2: 0.6286429138007592
Component: infra
    Job ID: 61625902[1], Model: MLP, Parameters: simple_mlp
    Best Policy Kendall Tau: 0.9369005233794834
    Policy Spearman: 0.9891829465919024
    Policy Aggregate Kendall Tau: 0.9597308843094928
    R2: 0.9974443374384782
Component: maintenance
    Job ID: 61618566, Model: GNN, Parameters: small_gnn
    Best Policy Kendall Tau: 0.9358643626706269
    Policy Spearman: 0.9868771765270389
    Policy Aggregate Kendall Tau: 0.9395009258367798
    R2: 0.9804639205117373
Component: qol
    Job ID: 61625903[0], Model: XGB, Parameters: small_xgb
    Best Policy Kendall Tau: 0.9996748418150013
    Policy Spearman: 0.9999996289495287
    Policy Aggregate Kendall Tau: 0.9717477274359689
    R2: 0.99998604818605

In [35]:
# profiles (== PARAMETERS) per model family


profiles = {
    "MLP":  ["simple_mlp", "deep_mlp", "wide_mlp", "large_mlp"],
    "Auto": ["small_bottleneck", "deep_bottleneck", "medium_bottleneck",
             "wide_bottleneck", "wide_xl_bottleneck", "large_bottleneck"],
    "VAE":  ["small_vae", "medium_vae", "wide_vae", "large_vae"],
    "GP":   ["tiny_gp", "small_gp", "medium_gp", "large_gp","xlarge_gp"], 
    "XGB":  ["small_xgb", "medium_xgb", "large_xgb"],
    "GNN": ["small_gnn", "medium_gnn", "deep_gnn","sage_gnn"]
}


# Plot table of each model's R2

for component in data["Component"].unique():
    print("\n")
    component_data = data[data["Component"] == component]
    print(f"Component: {component}")

    for model_family in profiles.keys():
        data_family = component_data[component_data["Model"] == model_family]
        # Get unique parameters for the model family present in data_family
        present_profiles = data_family["Parameters"].apply(lambda p: p["Profile"]).unique()
        print(f"Model Family: {model_family}")
        # Get the best R2 score for each profile in the model family
        for profile in present_profiles:
            profile_data = data_family[data_family["Parameters"].apply(lambda p: p["Profile"] == profile)]
            if not profile_data.empty:
                best_r2_row = profile_data.loc[
                    profile_data.apply(
                        lambda r: r["Test"].get("R2", float("nan")), axis=1
                    ).idxmax()
                ]
                best_test = best_r2_row["Test"]
                print(
                    f"    Profile: {profile}, Best Test R2: {best_test.get('R2')}, "
                    f"Policy Kendall Tau: {best_test.get('Policy Kendall Tau')}"
                )

Component: cancel
Model Family: MLP
    Profile: simple_mlp, Best Test R2: 0.11257032647109877, Policy Kendall Tau: 0.259325439610184
    Profile: deep_mlp, Best Test R2: 0.0026271450510172434, Policy Kendall Tau: 0.22717736142224979
    Profile: wide_mlp, Best Test R2: 0.23060399029491885, Policy Kendall Tau: 0.31163522840706653
Model Family: Auto
    Profile: small_bottleneck, Best Test R2: 0.026282002854009834, Policy Kendall Tau: 0.2073186890942732
    Profile: deep_bottleneck, Best Test R2: -0.10403905310604, Policy Kendall Tau: 0.17120378505144357
    Profile: medium_bottleneck, Best Test R2: -0.12180808147110112, Policy Kendall Tau: 0.16874673608081206
    Profile: wide_bottleneck, Best Test R2: -0.17108927537529728, Policy Kendall Tau: 0.15663908803609006
Model Family: VAE
    Profile: small_vae, Best Test R2: -0.1174001587939364, Policy Kendall Tau: 0.18187089720984503
    Profile: medium_vae, Best Test R2: -0.14523250034112034, Policy Kendall Tau: 0.1638214240634265
    Profile: wide_vae, Best Test R2: -0.1272261155661505, Policy Kendall Tau: 0.1790696189165578
    Profile: large_vae, Best Test R2: -0.09808411800397954, Policy Kendall Tau: 0.19532889418322794
Model Family: GP
Model Family: XGB
Model Family: GNN
    Profile: small_gnn, Best Test R2: 0.24632358914656638, Policy Kendall Tau: 0.3167231275269446


Component: qol
Model Family: MLP
    Profile: simple_mlp, Best Test R2: 0.9999631318247825, Policy Kendall Tau: 0.436588471598904
Model Family: Auto
Model Family: VAE
    Profile: small_vae, Best Test R2: 0.9999460021105553, Policy Kendall Tau: 0.43653917274301063
Model Family: GP
Model Family: XGB
    Profile: small_xgb, Best Test R2: 0.99998604818605, Policy Kendall Tau: 0.9996748418150013
Model Family: GNN
    Profile: small_gnn, Best Test R2: 0.999823019340621, Policy Kendall Tau: 0.43629509134057004


Component: action
Model Family: MLP
Model Family: Auto
Model Family: VAE
Model Family: GP
Model Family: XGB
Model Family: GNN
    Profile: small_gnn, Best Test R2: 0.9879413018451796, Policy Kendall Tau: 0.613338608082169


Component: maintenance
Model Family: MLP
    Profile: simple_mlp, Best Test R2: 0.9329634618015279, Policy Kendall Tau: 0.8565719625590213
Model Family: Auto
    Profile: small_bottleneck, Best Test R2: 0.914645494986177, Policy Kendall Tau: 0.8427038469577229
Model Family: VAE
    Profile: small_vae, Best Test R2: 0.9139261164418901, Policy Kendall Tau: 0.8429821075671347
Model Family: GP
Model Family: XGB
Model Family: GNN
    Profile: small_gnn, Best Test R2: 0.9804639205117373, Policy Kendall Tau: 0.9358643626706269


Component: delay
Model Family: MLP
    Profile: simple_mlp, Best Test R2: 0.6260234737309899, Policy Kendall Tau: 0.6965378364313479
    Profile: deep_mlp, Best Test R2: 0.6310934110976684, Policy Kendall Tau: 0.6983448511140001
Model Family: Auto
    Profile: small_bottleneck, Best Test R2: 0.6286429138007592, Policy Kendall Tau: 0.7002338601969201
    Profile: deep_bottleneck, Best Test R2: 0.6258886830636992, Policy Kendall Tau: 0.6989969822531525
    Profile: medium_bottleneck, Best Test R2: 0.6261733831899028, Policy Kendall Tau: 0.6997032642511657
    Profile: wide_bottleneck, Best Test R2: 0.6327275825834409, Policy Kendall Tau: 0.6976359278106083
Model Family: VAE
    Profile: small_vae, Best Test R2: 0.6242687751632279, Policy Kendall Tau: 0.6986566852842984
    Profile: medium_vae, Best Test R2: 0.5807449025946616, Policy Kendall Tau: 0.6784685498703286
    Profile: wide_vae, Best Test R2: 0.39496045934146007, Policy Kendall Tau: 0.6263247068373432
    Profile: large_vae, Best Test R2: 0.08558960141221628, Policy Kendall Tau: 0.6401598185722126
Model Family: GP
Model Family: XGB
Model Family: GNN


Component: infra
Model Family: MLP
    Profile: simple_mlp, Best Test R2: 0.9974443374384782, Policy Kendall Tau: 0.9369005233794834
Model Family: Auto
Model Family: VAE
Model Family: GP
Model Family: XGB
Model Family: GNN

In [23]:
best_test.keys()

dict_keys(['MSE', 'RMSE', 'MAE', 'R2', 'Max Absolute Error', 'Values', 'Policy Kendall Tau', 'Policy Spearman', 'Policy Metrics Note', 'Policy Aggregate Kendall Tau', 'Policy Aggregate Spearman', 'Policy Aggregate Metrics Note'])

In [27]:
# profiles (== PARAMETERS) per model family

data_df = data[data["Dataset"].isin(["econ_combined", "qol_combined"])]

profiles = {
    "MLP":  ["simple_mlp", "deep_mlp", "wide_mlp", "large_mlp"],
    "Auto": ["small_bottleneck", "deep_bottleneck", "medium_bottleneck",
             "wide_bottleneck", "wide_xl_bottleneck", "large_bottleneck"],
    "VAE":  ["small_vae", "medium_vae", "wide_vae", "large_vae"],
    "GP":   ["tiny_gp", "small_gp", "medium_gp", "large_gp","xlarge_gp"], 
    "XGB":  ["small_xgb", "medium_xgb", "large_xgb"],
    "GNN": ["small_gnn", "medium_gnn", "deep_gnn","sage_gnn"]
}


ALL_COMPONENTS = ["delay", "cancel", "infra", "qol", "action", "maintenance"]

# Plot table of each model's R2

for component in ALL_COMPONENTS:
    print("\n")
    component_data = data_df[data_df["Component"] == component]
    print(f"Component: {component}")

    for model_family in profiles.keys():
        data_family = component_data[component_data["Model"] == model_family]
        # Get unique parameters for the model family present in data_family
        present_profiles = data_family["Parameters"].apply(lambda p: p["Profile"]).unique()
        print(f"  Model Family: {model_family}")
        # Get the best R2 score for each profile in the model family
        for profile in present_profiles:
            profile_data = data_family[data_family["Parameters"].apply(lambda p: p["Profile"] == profile)]
            if not profile_data.empty:
                best_r2_row = profile_data.loc[
                    profile_data.apply(
                        lambda r: r["Test"].get("R2", float("nan")), axis=1
                    ).idxmax() ]
                
                
                best_test = best_r2_row["Test"]
                print(
                    f"    Profile: {profile}, Best Test R2: {round(best_test.get('R2'), 4)},, Job Id: {best_r2_row['Job Id']}, "
                    f"Policy Kendall Tau: {round(best_test.get('Policy Kendall Tau'), 4)}, RMSE: {round(best_test.get('RMSE'), 4)}"
                    
                )
                if str(best_r2_row['Job Id']) in best_R2_row['Job Id'].values:
                    print("    This is best!")

Component: delay
  Model Family: MLP
    Profile: simple_mlp, Best Test R2: 0.626,, Job Id: 61625857, Policy Kendall Tau: 0.6965, RMSE: 1803199.9401
    Profile: deep_mlp, Best Test R2: 0.6311,, Job Id: 61625859, Policy Kendall Tau: 0.6983, RMSE: 1790935.3908
  Model Family: Auto
    Profile: small_bottleneck, Best Test R2: 0.6286,, Job Id: 61625901[3], Policy Kendall Tau: 0.7002, RMSE: 1796873.7754
    Profile: deep_bottleneck, Best Test R2: 0.6259,, Job Id: 61625865, Policy Kendall Tau: 0.699, RMSE: 1803524.8704
    Profile: medium_bottleneck, Best Test R2: 0.6262,, Job Id: 61625867, Policy Kendall Tau: 0.6997, RMSE: 1802838.4952
    Profile: wide_bottleneck, Best Test R2: 0.6327,, Job Id: 61625869, Policy Kendall Tau: 0.6976, RMSE: 1786964.2719
    This is best!
  Model Family: VAE
    Profile: small_vae, Best Test R2: 0.6243,, Job Id: 61625871, Policy Kendall Tau: 0.6987, RMSE: 1807425.2983
    Profile: medium_vae, Best Test R2: 0.5807,, Job Id: 61625873, Policy Kendall Tau: 0.6785, RMSE: 1909241.5995
    Profile: wide_vae, Best Test R2: 0.395,, Job Id: 61625875, Policy Kendall Tau: 0.6263, RMSE: 2293578.4081
    Profile: large_vae, Best Test R2: 0.0856,, Job Id: 61625877, Policy Kendall Tau: 0.6402, RMSE: 2819631.091
  Model Family: GP
    Profile: tiny_gp, Best Test R2: 0.3036,, Job Id: 61661641, Policy Kendall Tau: 0.6135, RMSE: 2460586.4678
  Model Family: XGB
  Model Family: GNN


Component: cancel
  Model Family: MLP
    Profile: simple_mlp, Best Test R2: 0.1126,, Job Id: 61625858, Policy Kendall Tau: 0.2593, RMSE: 4364880.8682
    Profile: deep_mlp, Best Test R2: 0.0026,, Job Id: 61625860, Policy Kendall Tau: 0.2272, RMSE: 4627369.6491
    Profile: wide_mlp, Best Test R2: 0.2306,, Job Id: 61625862, Policy Kendall Tau: 0.3116, RMSE: 4064249.7389
  Model Family: Auto
    Profile: small_bottleneck, Best Test R2: 0.0263,, Job Id: 61625864, Policy Kendall Tau: 0.2073, RMSE: 4572166.3208
    Profile: deep_bottleneck, Best Test R2: -0.104,, Job Id: 61625866, Policy Kendall Tau: 0.1712, RMSE: 4868527.6367
    Profile: medium_bottleneck, Best Test R2: -0.1218,, Job Id: 61625868, Policy Kendall Tau: 0.1687, RMSE: 4907549.6701
    Profile: wide_bottleneck, Best Test R2: -0.1711,, Job Id: 61625870, Policy Kendall Tau: 0.1566, RMSE: 5014185.811
  Model Family: VAE
    Profile: small_vae, Best Test R2: -0.1174,, Job Id: 61625872, Policy Kendall Tau: 0.1819, RMSE: 4897898.558
    Profile: medium_vae, Best Test R2: -0.1452,, Job Id: 61625874, Policy Kendall Tau: 0.1638, RMSE: 4958522.1072
    Profile: wide_vae, Best Test R2: -0.1272,, Job Id: 61625876, Policy Kendall Tau: 0.1791, RMSE: 4919386.4738
    Profile: large_vae, Best Test R2: -0.0981,, Job Id: 61625878, Policy Kendall Tau: 0.1953, RMSE: 4855380.0195
  Model Family: GP
    Profile: tiny_gp, Best Test R2: 0.0285,, Job Id: 61661556, Policy Kendall Tau: 0.2445, RMSE: 4566988.2839
  Model Family: XGB
  Model Family: GNN
    Profile: small_gnn, Best Test R2: 0.2463,, Job Id: 61625904[2], Policy Kendall Tau: 0.3167, RMSE: 4022516.9519
    This is best!


Component: infra
  Model Family: MLP
    Profile: simple_mlp, Best Test R2: 0.9974,, Job Id: 61625902[1], Policy Kendall Tau: 0.9369, RMSE: 97499.6362
    This is best!
  Model Family: Auto
    Profile: small_bottleneck, Best Test R2: 0.9971,, Job Id: 61661631, Policy Kendall Tau: 0.9067, RMSE: 103811.2227
    Profile: medium_bottleneck, Best Test R2: 0.9972,, Job Id: 61661634, Policy Kendall Tau: 0.9084, RMSE: 101435.9952
  Model Family: VAE
    Profile: small_vae, Best Test R2: 0.997,, Job Id: 61661637, Policy Kendall Tau: 0.9011, RMSE: 105649.9814
    Profile: medium_vae, Best Test R2: 0.9971,, Job Id: 61661640, Policy Kendall Tau: 0.9001, RMSE: 103912.1219
  Model Family: GP
  Model Family: XGB
  Model Family: GNN


Component: qol
  Model Family: MLP
    Profile: simple_mlp, Best Test R2: 1.0,, Job Id: 61636922, Policy Kendall Tau: 0.4366, RMSE: 0.001
  Model Family: Auto
    Profile: small_bottleneck, Best Test R2: 1.0,, Job Id: 61636925, Policy Kendall Tau: 0.4367, RMSE: 0.0008
    Profile: medium_bottleneck, Best Test R2: 0.9999,, Job Id: 61661621, Policy Kendall Tau: 0.4365, RMSE: 0.0014
  Model Family: VAE
    Profile: small_vae, Best Test R2: 0.9999,, Job Id: 61636928, Policy Kendall Tau: 0.4365, RMSE: 0.0012
    Profile: medium_vae, Best Test R2: 0.9999,, Job Id: 61661623, Policy Kendall Tau: 0.4365, RMSE: 0.0014
  Model Family: GP
    Profile: tiny_gp, Best Test R2: 0.9998,, Job Id: 61661606, Policy Kendall Tau: 0.4364, RMSE: 0.0021
  Model Family: XGB
    Profile: small_xgb, Best Test R2: 1.0,, Job Id: 61625903[0], Policy Kendall Tau: 0.9997, RMSE: 0.0006
    This is best!
  Model Family: GNN
    Profile: small_gnn, Best Test R2: 0.9998,, Job Id: 61618564, Policy Kendall Tau: 0.4363, RMSE: 0.0022


Component: action
  Model Family: MLP
    Profile: simple_mlp, Best Test R2: 0.8899,, Job Id: 61636923, Policy Kendall Tau: 0.5182, RMSE: 23660687.5924
  Model Family: Auto
    Profile: small_bottleneck, Best Test R2: 0.4301,, Job Id: 61636926, Policy Kendall Tau: 0.3987, RMSE: 53824516.2124
    Profile: medium_bottleneck, Best Test R2: 0.4528,, Job Id: 61661621, Policy Kendall Tau: 0.3983, RMSE: 52744747.833
  Model Family: VAE
    Profile: small_vae, Best Test R2: 0.4588,, Job Id: 61636929, Policy Kendall Tau: 0.3979, RMSE: 52456058.7591
    Profile: medium_vae, Best Test R2: 0.2513,, Job Id: 61661623, Policy Kendall Tau: 0.3332, RMSE: 61694923.8884
  Model Family: GP
    Profile: tiny_gp, Best Test R2: 0.0328,, Job Id: 61661624, Policy Kendall Tau: 0.0243, RMSE: 70122644.9704
  Model Family: XGB
  Model Family: GNN
    Profile: small_gnn, Best Test R2: 0.9879,, Job Id: 61618565, Policy Kendall Tau: 0.6133, RMSE: 7829785.8187
    This is best!


Component: maintenance
  Model Family: MLP
    Profile: simple_mlp, Best Test R2: 0.933,, Job Id: 61636924, Policy Kendall Tau: 0.8566, RMSE: 242925.1461
  Model Family: Auto
    Profile: small_bottleneck, Best Test R2: 0.9146,, Job Id: 61636927, Policy Kendall Tau: 0.8427, RMSE: 274113.1732
    Profile: medium_bottleneck, Best Test R2: 0.9107,, Job Id: 61661621, Policy Kendall Tau: 0.84, RMSE: 280447.832
  Model Family: VAE
    Profile: small_vae, Best Test R2: 0.9139,, Job Id: 61636930, Policy Kendall Tau: 0.843, RMSE: 275265.8797
    Profile: medium_vae, Best Test R2: 0.9105,, Job Id: 61661623, Policy Kendall Tau: 0.8405, RMSE: 280735.2769
  Model Family: GP
    Profile: tiny_gp, Best Test R2: 0.7438,, Job Id: 61661624, Policy Kendall Tau: 0.7687, RMSE: 474918.6649
  Model Family: XGB
  Model Family: GNN
    Profile: small_gnn, Best Test R2: 0.9805,, Job Id: 61618566, Policy Kendall Tau: 0.9359, RMSE: 131140.0636
    This is best!